language: c

matrix:
  include:
    - sudo: false
      dist: bionic
      compiler: gcc
      env: CMPLR=gcc
    - sudo: false
      dist: xenial
      compiler: gcc
      env: CMPLR=gcc
    - sudo: false
      dist: bionic
      compiler: gcc
      env: CMPLR=gcc CMD_CXXFLAGS=-std=c++11
    - sudo: false
      dist: trusty
      compiler: gcc
      env: CMPLR=gcc STATIC=YES CMD_CXXFLAGS=-std=c++11
    - sudo: false
      dist: bionic
      compiler: gcc
      env: CMPLR=clang
    - sudo: false
      dist: xenial
      compiler: gcc
      env: CMPLR=clang
    - sudo: false
      dist: trusty
      compiler: gcc
      env: CMPLR=clang STATIC=YES
    - sudo: false
      dist: trusty
      compiler: gcc
      env: WINE=32 TEST=NO STATIC=YES
    - sudo: false
      dist: trusty
      compiler: gcc
      env: WINE=32 TEST=NO STATIC=NO
    - sudo: false
      dist: trusty
      compiler: gcc
      env: RTEMS=4.10
    - sudo: false
      dist: trusty
      compiler: gcc
      env: RTEMS=4.9
    - os: osx
      env: CMD_CFLAGS="-mmacosx-version-min=10.7" CMD_CXXFLAGS="-mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++" CMD_LDXFLAGS="-mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++"

addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - qemu-system-x86
script:
  - .ci/travis-prepare.sh
  - .ci/travis-build.sh
